In [1]:
import numpy as np
np.random.seed(123)
MAT = np.random.exponential( scale=1/5, size=(10, 7))
MAT = np.around( MAT, decimals=3)
MAT

array([[0.238, 0.067, 0.051, 0.16 , 0.254, 0.11 , 0.79 ],
       [0.231, 0.131, 0.1  , 0.084, 0.261, 0.115, 0.012],
       [0.102, 0.268, 0.04 , 0.039, 0.152, 0.152, 0.201],
       [0.379, 0.258, 0.189, 0.256, 0.078, 0.09 , 0.052],
       [0.07 , 0.199, 0.019, 0.114, 0.113, 0.136, 0.111],
       [0.075, 0.111, 0.448, 0.577, 0.139, 0.196, 0.025],
       [0.076, 0.107, 0.402, 0.058, 0.132, 0.848, 0.147],
       [0.19 , 0.026, 0.35 , 0.185, 0.158, 0.084, 0.073],
       [0.108, 0.229, 0.417, 0.143, 0.221, 0.176, 0.196],
       [0.225, 0.369, 0.017, 0.289, 0.056, 0.043, 0.17 ]])

In [5]:
Q1 = np.percentile( MAT, q=25)
Q3 = np.percentile( MAT, q=75)
MAT [ ( MAT < Q1- 1.5*(Q3-Q1) ) | ( MAT > Q3 + 1.5*(Q3-Q1) ) ] 

array([0.79 , 0.577, 0.848])

In [9]:
m = np.median( MAT )
mdiff = np.abs ( MAT - m )
np.nonzero ( mdiff == np.min ( mdiff ) )

(array([8], dtype=int64), array([3], dtype=int64))

In [12]:
MAT[ np.argsort(MAT[:, 1]), : ]

array([[0.19 , 0.026, 0.35 , 0.185, 0.158, 0.084, 0.073],
       [0.238, 0.067, 0.051, 0.16 , 0.254, 0.11 , 0.79 ],
       [0.076, 0.107, 0.402, 0.058, 0.132, 0.848, 0.147],
       [0.075, 0.111, 0.448, 0.577, 0.139, 0.196, 0.025],
       [0.231, 0.131, 0.1  , 0.084, 0.261, 0.115, 0.012],
       [0.07 , 0.199, 0.019, 0.114, 0.113, 0.136, 0.111],
       [0.108, 0.229, 0.417, 0.143, 0.221, 0.176, 0.196],
       [0.379, 0.258, 0.189, 0.256, 0.078, 0.09 , 0.052],
       [0.102, 0.268, 0.04 , 0.039, 0.152, 0.152, 0.201],
       [0.225, 0.369, 0.017, 0.289, 0.056, 0.043, 0.17 ]])

In [16]:
MAT  [  :  , np.argsort( np.mean( MAT, axis = 0 ) ) [::-1]  ]

array([[0.051, 0.11 , 0.16 , 0.79 , 0.067, 0.238, 0.254],
       [0.1  , 0.115, 0.084, 0.012, 0.131, 0.231, 0.261],
       [0.04 , 0.152, 0.039, 0.201, 0.268, 0.102, 0.152],
       [0.189, 0.09 , 0.256, 0.052, 0.258, 0.379, 0.078],
       [0.019, 0.136, 0.114, 0.111, 0.199, 0.07 , 0.113],
       [0.448, 0.196, 0.577, 0.025, 0.111, 0.075, 0.139],
       [0.402, 0.848, 0.058, 0.147, 0.107, 0.076, 0.132],
       [0.35 , 0.084, 0.185, 0.073, 0.026, 0.19 , 0.158],
       [0.417, 0.176, 0.143, 0.196, 0.229, 0.108, 0.221],
       [0.017, 0.043, 0.289, 0.17 , 0.369, 0.225, 0.056]])

In [17]:
MAT [ ( MAT < Q1- 1.5*(Q3-Q1) ) | ( MAT > Q3 + 1.5*(Q3-Q1) ) ] = np.nan
MAT

array([[0.238, 0.067, 0.051, 0.16 , 0.254, 0.11 ,   nan],
       [0.231, 0.131, 0.1  , 0.084, 0.261, 0.115, 0.012],
       [0.102, 0.268, 0.04 , 0.039, 0.152, 0.152, 0.201],
       [0.379, 0.258, 0.189, 0.256, 0.078, 0.09 , 0.052],
       [0.07 , 0.199, 0.019, 0.114, 0.113, 0.136, 0.111],
       [0.075, 0.111, 0.448,   nan, 0.139, 0.196, 0.025],
       [0.076, 0.107, 0.402, 0.058, 0.132,   nan, 0.147],
       [0.19 , 0.026, 0.35 , 0.185, 0.158, 0.084, 0.073],
       [0.108, 0.229, 0.417, 0.143, 0.221, 0.176, 0.196],
       [0.225, 0.369, 0.017, 0.289, 0.056, 0.043, 0.17 ]])

In [21]:
MAT[ np.sum ( np.isnan( MAT ) ,  axis = 1 )> 0 , : ]

array([[0.238, 0.067, 0.051, 0.16 , 0.254, 0.11 ,   nan],
       [0.075, 0.111, 0.448,   nan, 0.139, 0.196, 0.025],
       [0.076, 0.107, 0.402, 0.058, 0.132,   nan, 0.147]])

In [26]:
np.random.seed(123)
aMAT = np.random.randint ( 0, 100, (6, 10))
aVec = np.where( np.mean (aMAT , axis=0 ) > 50 , 1, 0 )
aVec

array([1, 1, 1, 1, 0, 1, 1, 1, 1, 0])

In [29]:
aMAT[  ( aMAT [:, 4] > 50 ) | ( aMAT [:, 6] < 30 ), : ]

array([[66, 92, 98, 17, 83, 57, 86, 97, 96, 47],
       [61, 48,  7, 99, 92, 52, 97, 85, 94, 27]])

In [32]:
aMAT [ [3, 1] , [1, 6] ] = 999
aMAT

array([[ 66,  92,  98,  17,  83,  57,  86,  97,  96,  47],
       [ 73,  32,  46,  96,  25,  83, 999,  36,  96,  80],
       [ 68,  49,  55,  67,   2,  84,  39,  66,  84,  47],
       [ 61, 999,   7,  99,  92,  52,  97,  85,  94,  27],
       [ 34,  97,  76,  40,   3,  69,  64,  75,  34,  58],
       [ 10,  22,  77,  18,  15,  27,  30,  52,  70,  26]])

In [37]:
aMAT [ ~ np.any( aMAT == 999, axis = 1 ), : ].mean(axis=0)

array([44.5 , 65.  , 76.5 , 35.5 , 25.75, 59.25, 54.75, 72.5 , 71.  ,
       44.5 ])

In [39]:
aMAT [ ~ np.any( aMAT == 999, axis = 1 ), : ].std(axis=0)

array([24.05722345, 31.05640031, 15.20690633, 20.37768387, 33.44678609,
       20.93292861, 21.92458666, 16.34778272, 23.2594067 , 11.58663023])