# Chp 5. Numpy

In [1]:
import numpy as np

In [2]:
np.__version__ # 최신 버전 쓰고 있음. 

'1.26.4'

- same dtype으로 array에 들어감. 

In [3]:
arr = np.array([
    [1.5, 1, 3],
    [2, 2, 2],
    ]) # 하나가 float이면 전체가 float

In [4]:
arr.ndim

2

In [5]:
arr.size

6

In [6]:
arr.shape

(2, 3)

In [7]:
arr.dtype # float의 default는 float64

dtype('float64')

- dtypes:
    - int32
    - int64
    - float32
    - float64
    - complex128
    - bool

- Empty array creation

틀 만들어놓고 시작하는 경우 유용

In [8]:
arr = np.zeros((3, 4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
arr = np.ones((3, 4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
arr = np.empty((3, 4))
arr # random한 값들이 채워져 있어야 하는데 1.0이 계속 들어가네. 이상하다...

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
arr[0, 0]

1.0

In [12]:
arr = np.eye(3)
arr # 3x3의 identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
arr = np.full((3, 4), 99.)
arr

array([[99., 99., 99., 99.],
       [99., 99., 99., 99.],
       [99., 99., 99., 99.]])

- sequence of number를 가지고 create하는 방법

In [14]:
arr = np.arange(1, 10, 0.1)
arr

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [15]:
arr = np.linspace(start=1, stop=10, num=50) # 1이상 10이하 50개의 숫자를 만들어라. 같은 간격. high도 포함됨.(이하)
arr

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

- random number creation

In [16]:
np.random.seed(42)

In [17]:
# uniform distribution (0~1)
arr = np.random.rand(3, 4) # shape가 들어감. tuple 아닌 채로. 
arr

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848],
       [0.15601864, 0.15599452, 0.05808361, 0.86617615],
       [0.60111501, 0.70807258, 0.02058449, 0.96990985]])

In [18]:
# uniform distribution (low~high)
arr = np.random.uniform(low=10, high=100, size=(3, 4))
arr

array([[84.91983767, 29.11051996, 26.36424705, 26.50640589],
       [37.38180187, 57.22807885, 48.87505168, 36.21062262],
       [65.06676053, 22.55444746, 36.29301837, 42.9725659 ]])

In [20]:
# standard normal distribution
arr = np.random.randn(3, 4) # shape가 들어감. tuple 아닌 채로.
arr

array([[-0.01349722, -1.05771093,  0.82254491, -1.22084365],
       [ 0.2088636 , -1.95967012, -1.32818605,  0.19686124],
       [ 0.73846658,  0.17136828, -0.11564828, -0.3011037 ]])

In [21]:
# normal distribution
arr = np.random.normal(loc=6, scale=4, size=(3, 4)) # loc: mean, scale: std
arr

array([[ 0.08591204,  3.12062317,  4.15744492, 10.2284889 ],
       [ 7.37447316, -1.05216062,  7.29633588,  4.45967088],
       [ 3.292312  ,  8.44670516, 10.12399809,  9.72512048]])

In [22]:
# random integer. discrete uniform distribution
arr = np.random.randint(low=1, high=100, size=(3, 4)) # 1이상 100미만의 정수를 3x4 matrix로 만들어라.
arr

array([[33,  5, 41, 28],
       [ 7, 73, 72, 12],
       [34, 33, 48, 23]])

이 외에도 `np.random` 내에 

- binomial, 
- chisquare, 
- exponential, 
- f, 
- normal, 
- poisson, 
- standard_t, 
- standard_normal, 
- uniform 

분포가 준비되어 있음. 

Exercise 1

Exercise 1 

- Create an 1 dimensional array of all the even integers from 30 to 70.
- Create an 3x5 array filled with 15 random numbers from a standard normal distribution.
- Create a 2 dimensional array with shape (2, 5) by randomly extracting 10 integers between 10 and 30 inclusive.
- Create an array of shape (5,6), filled with integer zeros.

In [23]:
arr = np.arange(30, 70+1)
arr

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

In [24]:
arr = np.random.randn(3, 5)
arr

array([[ 1.21217234,  1.2334968 , -1.57415529,  0.63795294, -2.04442302],
       [ 1.06948089, -0.93376284,  0.78420819, -0.61487576,  0.33289244],
       [-1.38071702, -0.28080629, -0.05981726,  0.96117377,  1.79428084]])

In [25]:
arr = np.random.randint(10, 30+1, (2, 5)) # inclusive하게 뽑으려면 +1 해줘야 함.
arr

array([[14, 16, 22, 24, 20],
       [13, 22, 16, 28, 11]])

In [26]:
arr = np.zeros((5, 6), dtype=int) # default는 floating point zero. integer로 뽑으려면 dtype을 지정해줘야 함.
arr

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [27]:
arr.dtype # int의 default는 int32

dtype('int32')

- accessing values in numpy arrays
    - indexing
    - slicing
    - numericalindexing
    - logical indexing (boolean masking)
        - masking은 진짜 중요함. Haafor에서의 기억...

- indexing
    - one-dimensional & multi-dimensional

In [28]:
arr = np.random.randn(3, 4) 
arr

array([[ 0.58068954, -1.46696789,  0.89262947, -0.10525713],
       [-0.95534644, -0.41476463, -1.39874088, -0.34408054],
       [ 0.75078589, -0.32762518, -0.86159805, -0.2581848 ]])

In [29]:
arr[0][2] # 아무도 이렇게 안 씀. 

0.8926294715061621

In [30]:
arr[0, 2]

0.8926294715061621

In [31]:
arr[2, :]

array([ 0.75078589, -0.32762518, -0.86159805, -0.2581848 ])

In [32]:
arr[:, 2]

array([ 0.89262947, -1.39874088, -0.86159805])

exercise 2

In [33]:
grid = np.arange(6) + np.arange(0, 60, 10).reshape(-1, 1)
grid

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [34]:
#1
grid[0, 3:5]

array([3, 4])

In [35]:
#2
grid[4:6, 4:6]

array([[44, 45],
       [54, 55]])

In [36]:
#3
grid[:, 2]

array([ 2, 12, 22, 32, 42, 52])

In [37]:
#4
grid[:, 2:3]

array([[ 2],
       [12],
       [22],
       [32],
       [42],
       [52]])

In [20]:
#5
grid[2:5:2, 0:5:2]

array([[20, 22, 24],
       [40, 42, 44]])

exercise 3

In [28]:
grid = np.zeros((8,8), dtype=np.int64)
grid

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)

In [29]:
grid[1::2, 0::2] = 1
grid

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0]], dtype=int64)

In [ ]:
grid

`np.newaxis` == None

In [30]:
a = np.array([1,2,3])
a.reshape(1,3)

array([[1, 2, 3]])

In [35]:
a[np.newaxis, :]

array([[1, 2, 3]])

In [34]:
a[None, :]

array([[1, 2, 3]])

In [32]:
a[:, None]

array([[1],
       [2],
       [3]])

그 외 shape manipulations

In [38]:
A = np.random.rand(2, 3)
A

array([[6.47690121e-01, 5.20376995e-04, 3.52568856e-01],
       [3.04781258e-01, 1.64655853e-01, 5.34089419e-01]])

In [39]:
A.flatten()

array([6.47690121e-01, 5.20376995e-04, 3.52568856e-01, 3.04781258e-01,
       1.64655853e-01, 5.34089419e-01])

In [40]:
A.flatten('F') # flatten with Fortran order. 위 아래 위래 위 아래 이런 식으로 column 먼저 flatten

array([6.47690121e-01, 3.04781258e-01, 5.20376995e-04, 1.64655853e-01,
       3.52568856e-01, 5.34089419e-01])

concatenation

In [42]:
x = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [43]:
y = np.array([
    [7, 8, 9],
    [10, 11, 12],
    [13, 14, 15]
])

In [44]:
np.concatenate([x, y], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [45]:
np.concatenate([x, y], axis=1) # 모양 안맞으면 에러 남. 

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 3

concat으로 쓰는 대신 명시적으로 

`vstack`, `hstack` 써주자. 

In [46]:
np.vstack([x, y])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [47]:
np.hstack([x, x])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [49]:
two = np.array([
    [1, 2],
    [3, 4]
])

one = np.array([5, 6])

np.column_stack([two, one]) # 이런거도 있긴한데 굳이.. 그냥 one을 reshape해서 column으로 만들어서 hstack해도 됨.

array([[1, 2, 5],
       [3, 4, 6]])

반대로 split으로 찢을 수도 있음

In [50]:
grid

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [57]:
np.vsplit(grid, 2) # 2개로 나눠라.

[array([[ 0,  1,  2,  3,  4,  5],
        [10, 11, 12, 13, 14, 15],
        [20, 21, 22, 23, 24, 25]]),
 array([[30, 31, 32, 33, 34, 35],
        [40, 41, 42, 43, 44, 45],
        [50, 51, 52, 53, 54, 55]])]

In [58]:
np.vsplit(grid, [2]) # 2번 인덱스에서 나눠라.

[array([[ 0,  1,  2,  3,  4,  5],
        [10, 11, 12, 13, 14, 15]]),
 array([[20, 21, 22, 23, 24, 25],
        [30, 31, 32, 33, 34, 35],
        [40, 41, 42, 43, 44, 45],
        [50, 51, 52, 53, 54, 55]])]

In [59]:
np.split(grid, [2], axis=0)

[array([[ 0,  1,  2,  3,  4,  5],
        [10, 11, 12, 13, 14, 15]]),
 array([[20, 21, 22, 23, 24, 25],
        [30, 31, 32, 33, 34, 35],
        [40, 41, 42, 43, 44, 45],
        [50, 51, 52, 53, 54, 55]])]

array끼리의 연산

원래는 element-wise. shape가 같아야 함. 

하지만 broadcasting이 가능한 경우는 ㄱㅊ

- `@` 와 `np.dot` 같음



그 외 universal function들이 있다. 

- `np.exp`
- `np.log`
- `np.log10`
- `np.sqrt`
    - `np.cbrt`도 있고 
    - `np.power` 쓸 수 있음. 
    - 아니면 그냥 `**(1/3) ` 이게 제일 깔끔하지
- `np.sin` 외 삼각함수 2종
- `np.rint`
    - nearest "even" integer로 감. 반올림이 아님. 2.5면 2로 가고 3.5면 4로 감. 
    - 반올림은 `np.round(9.3456, 2)` >> 9.35 써야. 
- `np.ceil` 올림
- `np.floor` 버림
- `np.abs`
- `np.isnan`
- `np.inf`


numpy broadcasting

- 차원의 shape가 같거나
- 적어도 둘 중 하나의 작은 dimension이 1이라 그걸 늘렸을 때 다른 array와 shape를 맞출 수 있어야 함. 


In [75]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [73]:
b = np.array([
    [4, 5, 6],
    [7, 8, 9]
])
b

array([[4, 5, 6],
       [7, 8, 9]])

In [76]:
a + b

array([[ 5,  7,  9],
       [ 8, 10, 12]])

aggregation operations 

이거 좋다. 속도가 빠름. 앵간한 것은 이걸로 해주는 것이 좋다. 

그리고 nan-safe version도 있음. nan 무시하고 연산. 

- `np.sum`, `np.nansum`
- `np.prod`, `np.nanprod`
- `np.mean`, `np.nanmean` 매우 소중하다
- `np.std`, `np.nanstd`
- `np.var`, `np.nanvar`
- `np.min`, `np.nanmin`
- `np.max`, `np.nanmax`
- `np.median`, `np.nanmedian` 
- `np.percentile`, `np.nanpercentile` 매우 소중하다
- `np.any` boolean으로 판단
- `np.all` boolean으로 판단

In [78]:
a = np.array([1, 2, 3, np.nan])
np.prod(a)

nan

In [79]:
np.nanprod(a)

6.0

sorting & searching function

이것들도 매우 중요하다. 

- `np.sort`
- `np.argsort` 특히 중요
- `np.argmax`, `np.argmin`
- `np.nonzero`
- `np.where(condition, [, x, y])` 매우 중요

In [95]:
p = np.random.randn(3, 4)
p

array([[ 0.65304831,  1.10268747, -1.84980294,  1.16863124],
       [-0.9853818 , -1.09394041, -2.87945689, -0.80317767],
       [-0.00485694, -0.38332331, -0.46252686, -1.11249735]])

In [92]:
np.where(p < 0)

(array([1, 1, 2], dtype=int64), array([0, 3, 3], dtype=int64))

condition만 들어가면 이렇게 참인 곳의 array만 shape 순으로 나옴. 

(3, 4)의 shape에서 row 먼저 좌표가 쭉 나오고, column 좌표가 그 다음에 나옴. 

condition 뒤에 x, y가 들어가면 true일 때 x, false일때 y의 그 자리에 있는 것을 반환. 

이 때 일반적으로 shape가 맞아야 하지만, broadcastable 하면 아래처럼 동작은 할 수 있음. 

근데 너무 헷갈리니까 그냥 얌전히 condtiion, x, y 모두 사이즈를 맞춰서 넣어주는 것이 좋음. 

In [93]:
# Condition: 2x2 boolean array
condition = np.array([[True, False],
                      [True, True]])

# x: 2x2 array
x = np.array([[1, 2],
              [3, 4]])

# y: 1x2 array
y = np.array([5, 6])

# Attempt to use numpy.where with incompatible shapes
result = np.where(condition, x, y)

print(result)


[[1 6]
 [3 4]]


In [97]:
p

array([[ 0.65304831,  1.10268747, -1.84980294,  1.16863124],
       [-0.9853818 , -1.09394041, -2.87945689, -0.80317767],
       [-0.00485694, -0.38332331, -0.46252686, -1.11249735]])

In [98]:
argmin = np.argmin(p)
argmin

6

위처럼, argmin 했을 때 그냥 flatten된 index가 나와서 불편함. row, column 위치가 나오지 않음. 

이 경우 아래와 같이 shape를 주고 위치를 원복하는 것이 좋음. 

In [99]:
np.unravel_index(argmin, p.shape)

(1, 2)