# Chp 5. Numpy

In [1]:
import numpy as np

In [2]:
np.__version__ # 최신 버전 쓰고 있음. 

'1.26.4'

- same dtype으로 array에 들어감. 

In [3]:
arr = np.array([
    [1.5, 1, 3],
    [2, 2, 2],
    ]) # 하나가 float이면 전체가 float

In [4]:
arr.ndim

2

In [5]:
arr.size

6

In [6]:
arr.shape

(2, 3)

In [8]:
arr.dtype # float의 default는 float64

dtype('float64')

- dtypes:
    - int32
    - int64
    - float32
    - float64
    - complex128
    - bool

- Empty array creation

틀 만들어놓고 시작하는 경우 유용

In [10]:
arr = np.zeros((3, 4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
arr = np.ones((3, 4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
arr = np.empty((3, 4))
arr # random한 값들이 채워져 있어야 하는데 1.0이 계속 들어가네. 이상하다...

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
arr[0, 0]

1.0

In [17]:
arr = np.eye(3)
arr # 3x3의 identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
arr = np.full((3, 4), 99.)
arr

array([[99., 99., 99., 99.],
       [99., 99., 99., 99.],
       [99., 99., 99., 99.]])

- sequence of number를 가지고 create하는 방법

In [25]:
arr = np.arange(1, 10, 0.1)
arr

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [32]:
arr = np.linspace(start=1, stop=10, num=50) # 1이상 10이하 50개의 숫자를 만들어라. 같은 간격. high도 포함됨.(이하)
arr

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

- random number creation

In [33]:
np.random.seed(42)

In [40]:
# uniform distribution (0~1)
arr = np.random.rand(3, 4) # shape가 들어감. tuple 아닌 채로. 
arr

array([[0.92630088, 0.65107703, 0.91495968, 0.85003858],
       [0.44945067, 0.09541012, 0.37081825, 0.66884125],
       [0.66592236, 0.59129779, 0.27472179, 0.56124343]])

In [41]:
# uniform distribution (low~high)
arr = np.random.uniform(low=10, high=100, size=(3, 4))
arr

array([[44.46341873, 97.45408859, 86.40224418, 74.9556569 ],
       [31.23864278, 33.04614905, 13.63902306, 73.95966007],
       [19.98017387, 49.54028517, 28.15472821, 90.61872361]])

In [38]:
# standard normal distribution
arr = np.random.randn(3, 4) # shape가 들어감. tuple 아닌 채로.
arr

array([[ 0.3229998 , -1.39341694, -2.17833425, -1.04389641],
       [ 0.17269371,  0.32419877,  0.74585954, -1.83658324],
       [ 0.56446424,  0.02550067,  0.47319325,  0.6591906 ]])

In [39]:
# normal distribution
arr = np.random.normal(loc=6, scale=4, size=(3, 4)) # loc: mean, scale: std
arr

array([[15.36298534, 10.28394075,  6.38566592,  7.67640842],
       [ 2.18788884,  1.80851759, -1.50270709,  0.53287144],
       [ 8.54522043,  2.37311733,  7.90417035, 11.21464507]])

In [37]:
# random integer. discrete uniform distribution
arr = np.random.randint(low=1, high=100, size=(3, 4)) # 1이상 100미만의 정수를 3x4 matrix로 만들어라.
arr

array([[71, 44,  8, 47],
       [35, 78, 81, 36],
       [50,  4,  2,  6]])

이 외 다양한 분포들이 준비되어 있음. 

Exercise 1

Exercise 1 

- Create an 1 dimensional array of all the even integers from 30 to 70.
- Create an 3x5 array filled with 15 random numbers from a standard normal distribution.
- Create a 2 dimensional array with shape (2, 5) by randomly extracting 10 integers between 10 and 30 inclusive.
- Create an array of shape (5,6), filled with integer zeros.

In [45]:
arr = np.arange(30, 70+1)
arr

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

In [48]:
arr = np.random.randn(3, 5)
arr

array([[-0.20969244, -0.77404293, -0.35977815,  0.72408325, -0.25576464],
       [ 0.8499212 , -1.31132423, -0.87030495, -0.50664322, -1.30995069],
       [ 2.94366342, -1.0962658 ,  0.91488432, -0.66606062, -0.51378749]])

In [61]:
arr = np.random.randint(10, 30+1, (2, 5)) # inclusive하게 뽑으려면 +1 해줘야 함.
arr

array([[24, 10, 14, 25, 28],
       [13, 12, 26, 26, 21]])

In [63]:
arr = np.zeros((5, 6), dtype=int) # default는 floating point zero. integer로 뽑으려면 dtype을 지정해줘야 함.
arr

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [65]:
arr.dtype # int의 default는 int32

dtype('int32')

- accessing values in numpy arrays
    - indexing
    - slicing
    - numericalindexing
    - logical indexing (boolean masking)
        - masking은 진짜 중요함. Haafor에서의 기억...

- indexing
    - one-dimensional & multi-dimensional

In [67]:
arr = np.random.randn(3, 4) 
arr

array([[-0.88385744,  0.15372511,  0.05820872, -1.1429703 ],
       [ 0.35778736,  0.56078453,  1.08305124,  1.05380205],
       [-1.37766937, -0.93782504,  0.51503527,  0.51378595]])

In [68]:
arr[0][2] # 아무도 이렇게 안 씀. 

0.058208718445999896

In [71]:
arr[0, 2]

0.058208718445999896

In [72]:
arr[2, :]

array([-1.37766937, -0.93782504,  0.51503527,  0.51378595])

In [73]:
arr[:, 2]

array([0.05820872, 1.08305124, 0.51503527])

exercise 2

In [11]:
grid = np.arange(6) + np.arange(0, 60, 10).reshape(-1, 1)
grid

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [12]:
#1
grid[0, 3:5]

array([3, 4])

In [13]:
grid[4:6, 4:6]

array([[44, 45],
       [54, 55]])

In [14]:
grid[:, 2]

array([ 2, 12, 22, 32, 42, 52])

In [19]:
grid[:, 2:3]

array([[ 2],
       [12],
       [22],
       [32],
       [42],
       [52]])

In [20]:
grid[2:5:2, 0:5:2]

array([[20, 22, 24],
       [40, 42, 44]])

exercise 3

In [28]:
grid = np.zeros((8,8), dtype=np.int64)
grid

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)

In [29]:
grid[1::2, 0::2] = 1
grid

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0]], dtype=int64)

In [ ]:
grid

`np.newaxis` == None

In [30]:
a = np.array([1,2,3])
a.reshape(1,3)

array([[1, 2, 3]])

In [35]:
a[np.newaxis, :]

array([[1, 2, 3]])

In [34]:
a[None, :]

array([[1, 2, 3]])

In [32]:
a[:, None]

array([[1],
       [2],
       [3]])